stages:
  - build
  - deploy

amd64 syncthing build:
  stage: yobasystems/alpine-docker:dind
  stage: build
  tags:
    - amd64
  script:
    - apk add --update git
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - cd alpine-syncthing-amd64/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:master -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64 .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:master
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64

arm32v7 syncthing build:
  stage: yobasystems/alpine-docker:armhf-dind
  stage: build
  tags:
    - armhf
  script:
    - apk add --update git
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - cd alpine-syncthing-armhf/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7 -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf -t $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf
    - docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7
    - docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf

arm64v8 syncthing build:
  stage: yobasystems/alpine-docker:aarch64-dind
  stage: build
  tags:
    - aarch64
  script:
    - apk add --update git
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - cd alpine-syncthing-aarch64/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8 -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64 .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64
    - docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8
    - docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64

Github Mirror:
  stage: deploy
  tags:
    - deploy
  script:
    - git push --mirror https://$GITHUB_USERNAME:$GITHUB_PASSWORD@$GITHUB_REPO
    - git push https://$GITHUB_USERNAME:$GITHUB_PASSWORD@$GITHUB_REPO HEAD:master

Bitbucket Mirror:
  stage: deploy
  tags:
    - deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$BB_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'bitbucket.org' >> ~/.ssh/known_hosts
    - git push --mirror git@$BITBUCKET_REPO
    - git push git@$BITBUCKET_REPO HEAD:master
