version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-syncthing-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-syncthing-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-syncthing-aarch64/
    schedule:
      interval: weekly